
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import {  } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      userMessage: "",
response: "",
loading: false,
error: null
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function AgentDemo(props) {
    
    
    return (
      <div>
        



<div style="max-width: 600px; margin: 40px auto; padding: 20px; font-family: sans-serif;"><h1 style="color: #7c3aed;">AI Chat Demo</h1><p style="color: #666; margin-bottom: 24px;">Powered by Claude via Speck.js</p><input type="text" value={state.userMessage.value} onInput={e => state.userMessage.value = e.target.value} placeholder="Ask me anything..." style="width: 100%; padding: 12px; border: 2px solid #e5e7eb; border-radius: 8px; font-size: 16px; box-sizing: border-box; margin-bottom: 16px;"></input><button onClick={async () => {
  if (!state.userMessage.value.trim()) return;
  state.loading.value = true;
  state.error.value = null;
  try {
    const agent = new window.SpeckAgent({
      purpose: 'You are helpful.',
      model: 'claude-sonnet-4-20250514',
      provider: 'anthropic',
      streaming: false
    });
    const result = await agent.send(state.userMessage.value);
    state.response.value = result.content;
    state.userMessage.value = '';
  } catch (err) {
    state.error.value = err.message;
  }
  state.loading.value = false;
}} style="width: 100%; padding: 12px; background: #7c3aed; color: white; border: none; border-radius: 8px; font-size: 16px; cursor: pointer;">{state.loading.value ? 'Thinking...' : 'Send'}</button>{state.error.value && (<div style="margin-top: 16px; padding: 16px; background: #fee2e2; border-radius: 8px; color: #991b1b;">{state.error.value}</div>)}{state.response.value && (<div style="margin-top: 16px; padding: 16px; background: #f3f4f6; border-radius: 8px;"><strong style="color: #7c3aed;">Claude:</strong><p style="margin-top: 8px; white-space: pre-wrap;">{state.response.value}</p></div>)}</div>
      </div>
    );
  }
