
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import {  } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      count: 0
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function Counter(props) {
    const increment = () => state.count.value++;
    
    return (
      <div>
        

<div ><h2 >Count:{state.count.value}</h2><button onClick={increment}>Increment</button></div>
      </div>
    );
  }
