
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import {  } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      count: 0
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function Counter(props) {
    const increment = () => state.count.value++; const decrement = () => state.count.value--;
    
    return (
      <div>
        

<div style="padding: 30px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 16px; text-align: center; max-width: 300px; margin: 20px auto; box-shadow: 0 10px 30px rgba(102, 126, 234, 0.3);"><h2 style="color: white; font-size: 3rem; margin: 0 0 20px 0; text-shadow: 2px 2px 4px rgba(0,0,0,0.2);">{state.count.value}</h2><div style="display: flex; gap: 10px; justify-content: center;"><button onClick={decrement} style="padding: 12px 24px; background: rgba(255,255,255,0.2); color: white; border: 2px solid rgba(255,255,255,0.3); border-radius: 8px; font-size: 1.1rem; font-weight: bold; cursor: pointer;">- Decrement</button><button onClick={increment} style="padding: 12px 24px; background: white; color: #764ba2; border: none; border-radius: 8px; font-size: 1.1rem; font-weight: bold; cursor: pointer; box-shadow: 0 4px 15px rgba(0,0,0,0.2);">+ Increment</button></div></div>
      </div>
    );
  }
