
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import {  } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function Header(props) {
    
    
    return (
      <div>
        <h1 >Welcome to SpeckJS</h1>
<p >AI-native. Modular. Fast.</p>
      </div>
    );
  }
