
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import {  } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      count: 0
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function SignalsDemo(props) {
    const increment = () => state.count.value++; const reset = () => state.count.value = 0;
    
    return (
      <div>
        

<div style="text-align: center;"><div style="background: linear-gradient(135deg, #667eea, #764ba2); color: white; border-radius: 50%; width: 120px; height: 120px; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center; font-size: 3rem; font-weight: bold; box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);">{state.count.value}</div><p style="color: #666; font-size: 1.1rem; margin-bottom: 20px;">{state.count.value === 0 && (<span >Click the button to start counting!</span>)}{state.count.value > 0 && state.count.value < 5 && (<span >Nice! Keep going!</span>)}{state.count.value >= 5 && state.count.value < 10 && (<span >You are on fire!</span>)}{state.count.value >= 10 && (<span >Amazing! You have mastered reactivity!</span>)}</p><div style="display: flex; gap: 10px; justify-content: center;"><button onClick={increment} style="background: linear-gradient(135deg, #667eea, #764ba2); color: white; border: none; padding: 15px 30px; border-radius: 10px; font-size: 1.1rem; font-weight: bold; cursor: pointer; box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4); transition: transform 0.2s;">+ Increment</button><button onClick={reset} style="background: #f3f4f6; color: #666; border: 2px solid #e5e7eb; padding: 15px 30px; border-radius: 10px; font-size: 1.1rem; font-weight: bold; cursor: pointer; transition: all 0.2s;">Reset</button></div><p style="color: #999; font-size: 0.9rem; margin-top: 20px; font-style: italic;">This updates instantly with zero re-renders!</p></div>
      </div>
    );
  }
