
  // ⚠️ AUTO-GENERATED BY SPECK. DO NOT EDIT.
  // This file was compiled from a .speck component.
  
  import { h } from 'preact';
  import { useEffect, useState } from 'preact/hooks';
  import { signal, computed, effect, batch } from '@preact/signals';

  import { Agent } from './_componentRegistry.js';
  
  // ✅ Fine-grained reactivity with signals
  const state = {
      
  };
  
  // Convert state values to signals for fine-grained reactivity
  Object.keys(state).forEach(key => {
    state[key] = signal(state[key]);
  });

    export default function SimpleChat(props) {
    
    
    return (
      <div>
        <div style="max-width: 600px; margin: 0 auto; padding: 20px; font-family: sans-serif;"><h1 style="color: #7c3aed;">💬 Simple Chat</h1><p style="color: #666;">One line of code. Full chat UI.</p><Agent.Chat id="simple-chat" purpose="You are a friendly assistant who gives concise, helpful answers." memory={true} /></div>
      </div>
    );
  }
